name: "Deploy flows"
description: "Deploy flows to Prefect Cloud and Google Cloud Run"

inputs:
  prefect_api_key:
    description: "Prefect Cloud API key"
    required: true
  prefect_api_url:
    description: "Prefect Cloud API URL"
    required: true
  flow_entrypoint:
    description: "Prefect flow entrypoint e.g. myflow.py:flow_function"
    required: true
  deployment:
    description: "Prefect deployment name - could reference environment or branch name e.g. dev or prod"
    required: true
    default: chess-ratings-dev-deployment
  queue:
    description: "Prefect queue name"
    required: true
    default: chess-ratings-dev-queue
  infrastructure_block:
    description: "Name of the infrastructure block"
    required: true
    default: cloud-run-job/chess-ratings-dev

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install dependencies
      shell: bash
      run: poetry install --no-interaction

    - name: Configure Prefect credentials
      id: login-prefect
      run: |
        prefect config set PREFECT_API_KEY=${{ inputs.prefect_api_key }}
        prefect config set PREFECT_API_URL=${{ inputs.prefect_api_url }}
      shell: bash

    - name: Run Prefect Deployment build
      run: |
        poetry run prefect deployment build ${{ inputs.flow_entrypoint }} -n ${{ inputs.deployment }} -q ${{ inputs.queue }} \
        -sb "${{ inputs.storage_block }}" -ib "${{ inputs.infrastructure_block }}" --skip-upload -a -v $GITHUB_SHA
      shell: bash
